services:
  bot:
    build: .
    container_name: namunara_bot
    restart: unless-stopped
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - namunara_network

networks:
  namunara_network:
    external: true